export const seedData = {
  users: {
    _model: "User",
    kieron: {
      firstName: "Kieron",
      lastName: "Garvey",
      email: "k@g.com",
      password: "1",
      accountType: "superadmin",
    },
    homer: {
      firstName: "Homer",
      lastName: "Simpson",
      email: "homer@simpson.com",
      password: "secret",
      accountType: "user",
    },
    marge: {
      firstName: "Marge",
      lastName: "Simpson",
      email: "marge@simpson.com",
      password: "secret",
      accountType: "user",
    },
    bart: {
      firstName: "Bart",
      lastName: "Simpson",
      email: "bart@simpson.com",
      password: "secret",
      accountType: "user",
    },
  },
  clubs: {
    _model: "Club",
    ballina: {
      club: "Ballina",
      address: "Mayo",
      phone: "0867896523",
      email: "info@ballinarfc.com",
      website: "https://www.ballinarfc.com",
      latitude: "54.1309827",
      longitude: "-9.1318907",
      description: "Ballina Rugby Football Club is a rugby union club based in Mayo",
      category: "SENIOR",
      userId: "->users.marge",
    },
    ballymena: {
      club: "Ballymena",
      address: "Antrim",
      phone: "0867896524",
      email: "info@ballymenarfc.com",
      website: "http://www.ballymenarfc.com",
      latitude: "54.8785161",
      longitude: "-6.2430095",
      description: "Ballymena Rugby Football Club is a rugby union club based in Antrim",
      category: "JUNIOR",
      userId: "->users.bart",
    },
    ballynahinch: {
      club: "Ballynahinch",
      address: "Ballynahinch",
      phone: "0867896525",
      email: "info@hinchrfc.co.uk",
      website: "http://www.hinchrfc.co.uk",
      latitude: "54.3866921",
      longitude: "-5.9147424",
      description: "Ballynahinch Rugby Football Club is a rugby union club based in Ballynahinch",
      category: "SENIOR",
      userId: "->users.homer",
    },
    banbridge: {
      club: "Banbridge",
      address: "Down",
      phone: "0867896526",
      email: "info@banbridgerfc.com",
      website: "https://www.banbridgerfc.com",
      latitude: "54.3429214",
      longitude: "-6.2720673",
      description: "Banbridge Rugby Football Club is a rugby union club based in Down",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    bangor: {
      club: "Bangor",
      address: "Down",
      phone: "0867896527",
      email: "info@bangorrfc.com",
      website: "https://www.bangorrfc.com",
      latitude: "54.641705",
      longitude: "-5.654943",
      description: "Bangor Rugby Football Club is a rugby union club based in Down",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    bective_rangers: {
      club: "Bective Rangers",
      address: "Dublin",
      phone: "0867896528",
      email: "info@http://bectiverangers.com",
      website: "http://bectiverangers.com",
      latitude: "53.321474",
      longitude: "-6.2351573",
      description: "Bective Rangers Rugby Football Club is a rugby union club based in Dublin",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    belfast_harlequins: {
      club: "Belfast Harlequins",
      address: "Belfast",
      phone: "0867896529",
      email: "info@http://harlequins.com",
      website: "http://harlequins.com",
      latitude: "54.5627109",
      longitude: "-5.940114",
      description: "Belfast Harlequins Rugby Football Club is a rugby union club based in Belfast",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    blackrock: {
      club: "Blackrock College",
      address: "Dublin",
      phone: "0867896530",
      email: "info@blackrockcollegerfc.ie",
      website: "https://www.blackrockcollegerfc.ie",
      latitude: "53.2902201",
      longitude: "-6.1654871",
      description: "Blackrock College Rugby Football Club is a rugby union club based in Dublin",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    bruff: {
      club: "Bruff",
      address: "Limerick",
      phone: "0867896531",
      email: "info@bruffrfc.com",
      website: "http://www.bruffrfc.com",
      latitude: "52.4853318",
      longitude: "-8.5073652",
      description: "Bruff Rugby Football Club is a rugby union club based in Limerick",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    buccaneers: {
      club: "Buccaneers",
      address: "Westmeath",
      phone: "0867896532",
      email: "nfo@buccaneersrfc.com",
      website: "https://buccaneersrfc.com",
      latitude: "53.435416",
      longitude: "-7.9230912",
      description: "Buccaneers Rugby Football Club is a rugby union club based in Westmeath",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    cashel: {
      club: "Cashel",
      address: "Tipperary",
      phone: "0867896533",
      email: "nfo@cashelrfc.com",
      website: "https://cashelrfc.com",
      latitude: "52.5041922",
      longitude: "-7.8867689",
      description: "Cashel Rugby Football Club is a rugby union club based in Tipperary",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    armagh: {
      club: "City of Armagh",
      address: "Armagh",
      phone: "0867896534",
      email: "info@cityofarmaghrfc.com",
      website: "https://www.cityofarmaghrfc.com",
      latitude: "54.3434739",
      longitude: "-6.6512132",
      description: "City of Armagh Rugby Football Club is a rugby union club based in Armagh",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    derry: {
      club: "City of Derry",
      address: "Derry",
      phone: "0867896535",
      email: "info@cityofderryrfc.com",
      website: "https://www.cityofderryrfc.com",
      latitude: "55.0189882",
      longitude: "-7.2657674",
      description: "City of Derry Rugby Football Club is a rugby union club based in Derry",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    clontarf: {
      club: "Clontarf",
      address: "Dublin",
      phone: "0867896536",
      email: "info@clontarfrugby.com",
      website: "https://www.clontarfrugby.com",
      latitude: "53.3655543",
      longitude: "-6.20473",
      description: "Clontarf Rugby Football Club is a rugby union club based in Dublin",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    corinthians: {
      club: "Corinthians",
      address: "Galway",
      phone: "0867896537",
      email: "info@galwaycorinthians.com",
      website: "http://www.galwaycorinthians.com",
      latitude: "53.3195562",
      longitude: "-8.9912492",
      description: "Corinthians Rugby Football Club is a rugby union club based in Galway",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    constitution: {
      club: "Cork Constitution",
      address: "Cork",
      phone: "0867896538",
      email: "info@corkcon.ie",
      website: "http://www.corkcon.ie",
      latitude: "51.8902538",
      longitude: "-8.4335806",
      description: "Cork Constitution Rugby Football Club is a rugby union club based in Cork",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    dolphin: {
      club: "Dolphin",
      address: "Cork",
      phone: "0867896539",
      email: "info@dolphinrfc.com",
      website: "https://dolphinrfc.com",
      latitude: "51.8827354",
      longitude: "-8.4799455",
      description: "Dolphin Rugby Football Club is a rugby union club based in Cork",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    dublin_university: {
      club: "Dublin University",
      address: "Dublin",
      phone: "0867896540",
      email: "info@dufc.ie",
      website: "https://www.dufc.ie",
      latitude: "53.3451121",
      longitude: "-6.253342",
      description: "Dublin University Rugby Football Club is a rugby union club based in Dublin",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    dungannon: {
      club: "Dungannon",
      address: "Dungannon",
      phone: "0867896541",
      email: "nfo@dungannonrugby.com",
      website: "https://dungannonrugby.com",
      latitude: "54.4923825",
      longitude: "-6.7477354",
      description: "Dungannon Rugby Football Club is a rugby union club based in Dungannon",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    galwegians: {
      club: "Galwegians",
      address: "Galway",
      phone: "0867896542",
      email: "nfo@galwegians.ie",
      website: "https://galwegians.ie",
      latitude: "53.279766",
      longitude: "-9.0153441",
      description: "Galwegians Rugby Football Club is a rugby union club based in Galway",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    garryowen: {
      club: "Garryowen",
      address: "Limerick",
      phone: "0867896543",
      email: "info@http://garryowenrugby.com",
      website: "http://garryowenrugby.com",
      latitude: "52.631856",
      longitude: "-8.6433334",
      description: "Garryowen Rugby Football Club is a rugby union club based in Limerick",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    greystones: {
      club: "Greystones",
      address: "Wicklow",
      phone: "0867896544",
      email: "info@greystonesrfc.ie",
      website: "https://www.greystonesrfc.ie",
      latitude: "53.1342889",
      longitude: "-6.0665366",
      description: "Greystones Rugby Football Club is a rugby union club based in Wicklow",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    highfield: {
      club: "Highfield",
      address: "Cork",
      phone: "0867896545",
      email: "info@highfieldrfc.ie",
      website: "http://www.highfieldrfc.ie",
      latitude: "51.8861684",
      longitude: "-8.5177116",
      description: "Highfield Rugby Football Club is a rugby union club based in Cork",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    lansdowne: {
      club: "Lansdowne",
      address: "Dublin",
      phone: "0867896546",
      email: "nfo@lansdownerugby.com",
      website: "https://lansdownerugby.com",
      latitude: "53.3339878",
      longitude: "-6.2304032",
      description: "Lansdowne Rugby Football Club is a rugby union club based in Dublin",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    malahide: {
      club: "Malahide",
      address: "Dublin",
      phone: "0867896547",
      email: "info@http://malahiderfc.ie",
      website: "http://malahiderfc.ie",
      latitude: "53.4598819",
      longitude: "-6.1892473",
      description: "Malahide Rugby Football Club is a rugby union club based in Dublin",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    malone: {
      club: "Malone",
      address: "Belfast",
      phone: "0867896548",
      email: "info@malone-rfc.com",
      website: "https://www.malone-rfc.com",
      latitude: "54.5832476",
      longitude: "-5.8984904",
      description: "Malone Rugby Football Club is a rugby union club based in Belfast",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    midleton: {
      club: "Midleton",
      address: "Cork",
      phone: "0867896549",
      email: "nfo@midletonrugby.com",
      website: "https://midletonrugby.com",
      latitude: "51.9143321",
      longitude: "-8.1726276",
      description: "Midleton Rugby Football Club is a rugby union club based in Cork",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    barnhall: {
      club: "MU Barnhall",
      address: "Kildare",
      phone: "0867896550",
      email: "nfo@mubarnhall.com",
      website: "https://mubarnhall.com",
      latitude: "53.3638428",
      longitude: "-6.4900033",
      description: "MU Barnhall Rugby Football Club is a rugby union club based in Kildare",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    naas: {
      club: "Naas",
      address: "Kildare",
      phone: "0867896551",
      email: "info@naasrugby.com",
      website: "http://www.naasrugby.com",
      latitude: "53.2205654",
      longitude: "-6.6593079",
      description: "Naas Rugby Football Club is a rugby union club based in  Kildare",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    navan: {
      club: "Navan",
      address: "Meath",
      phone: "0867896552",
      email: "nfo@navanrfc.ie",
      website: "https://navanrfc.ie",
      latitude: "53.6413281",
      longitude: "-6.6703205",
      description: "Navan Rugby Football Club is a rugby union club based in Meath",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    nenagh: {
      club: "Nenagh Ormond",
      address: "Tyone",
      phone: "0867896553",
      email: "info@nenaghormondrfc.com",
      website: "http://www.nenaghormondrfc.com",
      latitude: "52.85383",
      longitude: "-8.18136",
      description: "Nenagh Ormond Rugby Football Club is a rugby union club based in Tyone",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    old_belvdere: {
      club: "Old Belvedere",
      address: "Dublin",
      phone: "0867896554",
      email: "info@oldbelvedere.ie",
      website: "http://www.oldbelvedere.ie",
      latitude: "53.321205",
      longitude: "-6.2285833",
      description: "Old Belvedere Rugby Football Club is a rugby union club based in Dublin",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    old_cresent: {
      club: "Old Crescent",
      address: "Limerick",
      phone: "0867896555",
      email: "info@oldcrescentrfc.com",
      website: "https://www.oldcrescentrfc.com",
      latitude: "52.6325587",
      longitude: "-8.6345568",
      description: "Old Crescent Rugby Football Club is a rugby union club based in Limerick",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    old_wesley: {
      club: "Old Wesley",
      address: "Dublin",
      phone: "0867896556",
      email: "info@oldwesley.ie",
      website: "https://www.oldwesley.ie",
      latitude: "53.3202478",
      longitude: "-6.232729",
      description: "Old Wesley Rugby Football Club is a rugby union club based in Dublin",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    omagh: {
      club: "Omagh",
      address: "Omagh",
      phone: "0867896557",
      email: "nfo@omaghrfc.com",
      website: "https://omaghrfc.com",
      latitude: "54.6162568",
      longitude: "-7.3371847",
      description: "Omagh Rugby Football Club is a rugby union club based in Omagh",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    queens_university: {
      club: "Queens University",
      address: "Belfast",
      phone: "0867896558",
      email: "info@http://qubrfc.com",
      website: "http://qubrfc.com",
      latitude: "54.5567192",
      longitude: "-5.960418",
      description: "Queens University Rugby Football Club is a rugby union club based in Belfast",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    seapoint: {
      club: "Seapoint",
      address: "Dublin",
      phone: "0867896559",
      email: "info@seapointrugby.com",
      website: "https://www.seapointrugby.com",
      latitude: "53.2583524",
      longitude: "-6.1374647",
      description: "Seapoint Rugby Football Club is a rugby union club based in Dublin",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    shannon: {
      club: "Shannon",
      address: "Limerick",
      phone: "0867896560",
      email: "nfo@shannonrfc.com",
      website: "https://shannonrfc.com",
      latitude: "52.6742173",
      longitude: "-8.6424898",
      description: "Shannon Rugby Football Club is a rugby union club based in Limerick",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    skerries: {
      club: "Skerries",
      address: "Dublin",
      phone: "0867896561",
      email: "info@skerriesrfc.ie",
      website: "https://www.skerriesrfc.ie",
      latitude: "53.572244",
      longitude: "-6.1009832",
      description: "Skerries Rugby Football Club is a rugby union club based in Dublin",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    sligo: {
      club: "Sligo",
      address: "Sligo",
      phone: "0867896562",
      email: "info@sligorfc.ie",
      website: "https://www.sligorfc.ie",
      latitude: "54.2710598",
      longitude: "-8.5850805",
      description: "Sligo Rugby Football Club is a rugby union club based in Sligo",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    marys_college: {
      club: "St Marys College",
      address: "Dublin",
      phone: "0867896563",
      email: "nfo@stmaryscollegerfc.com",
      website: "https://stmaryscollegerfc.com",
      latitude: "53.3033027",
      longitude: "-6.3111018",
      description: "St Marys College Rugby Football Club is a rugby union club based in Dublin",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    sundays_well: {
      club: "Sundays Well",
      address: "Cork",
      phone: "0867896564",
      email: "info@http://sundayswellrfc.com",
      website: "http://sundayswellrfc.com",
      latitude: "51.8800845",
      longitude: "-8.4708678",
      description: "Sundays Well Rugby Football Club is a rugby union club based in Cork",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    terenure_college: {
      club: "Terenure College",
      address: "Dublin",
      phone: "0867896565",
      email: "nfo@tcrfc.ie",
      website: "https://tcrfc.ie",
      latitude: "53.3061092",
      longitude: "-6.2909027",
      description: "Terenure College Rugby Football Club is a rugby union club based in Dublin",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    thomond: {
      club: "Thomond",
      address: "Limerick",
      phone: "0867896566",
      email: "nfo@thomondrfc.com",
      website: "https://thomondrfc.com",
      latitude: "52.6800206",
      longitude: "-8.6509759",
      description: "Thomond Rugby Football Club is a rugby union club based in Limerick",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    tullamore: {
      club: "Tullamore",
      address: "Offaly",
      phone: "0867896567",
      email: "info@tullamorerugby.com",
      website: "https://www.tullamorerugby.com",
      latitude: "53.2660828",
      longitude: "-7.4937107",
      description: "Tullamore Rugby Football Club is a rugby union club based in Offaly",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    ucc: {
      club: "UCC",
      address: "Cork",
      phone: "0867896568",
      email: "nfo@rugby.ucc.ie",
      website: "https://rugby.ucc.ie",
      latitude: "51.894493",
      longitude: "-8.5002863",
      description: "UCC Rugby Football Club is a rugby union club based in Cork",
      category: "JUNIOR",
      userId: "->users.kieron",
    },
    ucd: {
      club: "UCD",
      address: "Dublin",
      phone: "0867896569",
      email: "info@http://ucdrugby.com",
      website: "http://ucdrugby.com",
      latitude: "53.3075572",
      longitude: "-6.2261514",
      description: "UCD Rugby Football Club is a rugby union club based in Dublin",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    ulb: {
      club: "UL Bohemian",
      address: "Limerick",
      phone: "0867896570",
      email: "nfo@ulbohemians.com",
      website: "https://ulbohemians.com",
      latitude: "52.6710563",
      longitude: "-8.5310221",
      description: "UL Bohemian Rugby Football Club is a rugby union club based in Limerick",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    wanderers: {
      club: "Wanderers",
      address: "Dublin",
      phone: "0867896571",
      email: "info@wanderers.ie",
      website: "https://www.wanderers.ie",
      latitude: "53.3228864",
      longitude: "-6.2208627",
      description: "Wanderers Rugby Football Club is a rugby union club based in Dublin ",
      category: "SENIOR",
      userId: "->users.kieron",
    },
    young_munster: {
      club: "Young Munster",
      address: "Limerick",
      phone: "0867896572",
      email: "info@youngmunster.com",
      website: "http://www.youngmunster.com",
      latitude: "52.6457726",
      longitude: "-8.6291712",
      description: "Young Munster Rugby Football Club is a rugby union club based in Limerick",
      category: "SENIOR",
      userId: "->users.kieron",
    },
  },
  games: {
    _model: "Game",
    ballina: {
      home: "Ballina RFC",
      homescore: 12,
      awayscore: 22,
      away: "Young Munster RFC",
      gametime: "12:00",
      gamelocation: "Ballina RFC",
      clubid: "->clubs.ballina",
    },
    ballynahinch: {
      home: "Ballynahinch RFC",
      homescore: 29,
      awayscore: 10,
      away: "Wanderers RFC",
      gametime: "14:00",
      gamelocation: "343Clare RFC44",
      clubid: "->clubs.ballynahinch",
    },
  },
};
